events {
    worker_connections 1024;
}

http {
    # http reverse proxy on port 80
    server {
        
        listen 80;
        server_name _;

        location / {
            proxy_pass http://webclient:81/;
        }

        location /webclient {
            proxy_pass http://webclient:81/;
        }

        location /services {
            proxy_pass http://rest-service:8080/api/;
        }
    }
}