events {
    worker_connections 1024;
}

http {
    # http reverse proxy on port 80
    server {
        
        listen 80;
        server_name _;

        location / {
            proxy_pass http://ui:81/;  
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }

        location /ui/ { 
            proxy_pass http://ui:81/;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }


        # / postfix nötig, um /dashboard/... URLs ohne /dashboard weiterzuleiten

        location /dashboard/ {
            proxy_pass http://dashboard:82/;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }

        location /services/ {
            proxy_pass http://user-station-service:8080/api;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }
    }
}