#http {
  server {
    listen 81;
    server_name reverse-proxy;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
    }
  }
#}
