name : campus_day_app
version: '1'

networks:
  campus_day_app:  # Define the custom network
    driver: bridge    # Use the bridge driver

services:

  # nginx reverse proxy
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy-campus-day
    depends_on:
      - ui
      - user-station-service
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks: # attach to custom bridge network
      - campus_day_app
    hostname: reverse-proxy # set custom DNS name within bridge network
    expose:
      - 80  # open port within container
    ports:
      - "80:80"
    restart: always



  # angular client app + nginx webserver
  ui:
    image: ui
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    networks: # attach to custom bridge network
      - campus_day_app
    hostname: ui # set custom DNS name within bridge network
    expose:
      - 81  # open port within container
    ports:
      - "4201:81" # forword port 80 on bridge network to port 4200 on host
    restart: unless-stopped



  # angular client app + nginx webserver
  dashboard:
    image: dashboard
    container_name: dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    networks: # attach to custom bridge network
      - campus_day_app
    hostname: dashboard # set custom DNS name within bridge network
    expose:
      - 82  # open port within container
    ports:
      - "4202:82" # forword port 80 on bridge network to port 4200 on host
    restart: unless-stopped


  # datenbank
  postgres:
    image:               postgres:15
    container_name:      datenbank
    restart:             unless-stopped
    networks:
      - campus_day_app
    hostname:            database
    expose:
      # Containerport 5432 öffnen
      - 5432
    ports:
      # Containerport 5432 auf Hostport 5000 mappen
      # auskommentieren, damit DB nicht mehr über localhost zugänglich ist
      # anschalten, um DB über localhost zu debuggen / testen
      - "5000:5432"
    environment:
      # implizit neu zu erstellender Nutzer, Password und Datenbank
      POSTGRES_USER:     campus_day_app
      POSTGRES_PASSWORD: campus_day_app
      POSTGRES_DB:       campus_day_app
    volumes:
      # Datenbankinhalt
      - data:/var/lib/postgresql/data


  # server
  user-station-service:
    image:               user-station-service
    container_name:      user-station-service
    restart:             unless-stopped
    build:
      context: ./campus-day-webservice
      dockerfile: Dockerfile
    networks:
      - campus_day_app
    hostname:            rest-service
    expose:
      - 8080
    ports:
      - "8080:8080"

volumes:
  data: {}
