spring.application.name=server
server.port=8080

#server.port=8443
#server.ssl.key-alias=SERVER_SSL_KEY
#server.ssl.key-store-password=SERVER_SSL_KEY
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-type=PKCS12
